version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8081:80"
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
