version: "3.9"

services:
  db:
    build: ./db
    volumes:
      - sqlite_data:/data
    networks: [internal]

  backend:
    build: ./backend
    environment:
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - DB_PATH=/data/main.db
    volumes:
      - sqlite_data:/data
    ports:
      - "8000:8000"
    depends_on: [db]
    networks: [internal]

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Changé de 80:80 à 3000:80
    depends_on: [backend]
    networks: [internal]

  nginx:
    build: ./infra/nginx
    ports:
      - "8081:80"  # Nginx reste sur 8081
    depends_on: [frontend, backend]
    networks: [internal]

networks:
  internal:

volumes:
  sqlite_data: