services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - lan

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  lan:
    build:
      context: .
      dockerfile: Dockerfile.lan
    container_name: lan
    ports:
      - "8081:8081"
